spring:
  cloud:
    gateway:
      routes:
        # RUTA 1: Servicio de Usuarios
        - id: innovatube-usuarios
          uri: lb://innovatube-usuarios
          predicates:
            - Path=/Usuarios/**
            
        # RUTA 2: Servicio JWT
        - id: innovatube-jwt
          uri: lb://innovatube-jwt
          predicates:
            - Path=/jwt/**

      # CORS (Centralizado)
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:4200"
              - "https://innovatubeweb.netlify.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true